apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-site
  template:
    metadata:
      labels:
        app: portfolio-site
    spec:
      containers:
      - name: portfolio-site
        image: portfolio-site:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
